### PR TITLE
Shore up Firefox kiosk mode

### PR DESCRIPTION
**Pull request by gStart9**

### CODE REVIEW

**Comment by gStart9** [comment]
**Summary**:
Add the `kiosk` user
Make the kiosk user be the one to run the kiosk process
Add a few more about:config options to disable internet calls that Firefox makes automatically
re-arrange the user_pref list to be alphabetical to facilitate future edits

I'm missing something though -- not sure how best to test this.  I entered chroot-and-upgrade mode and changed the enable-kiosk script on a running test system and rebooted, but start9 still started the kiosk process:
```
root        5518  0.0  0.0  10280  5468 tty1     Ss+  20:33   0:00 /bin/login -f
start9      5556  0.1  0.0   2480  1676 tty1     S+   20:33   0:00  \_ /bin/sh /usr/bin/startx /home/start9/kiosk.sh
start9      5584  0.0  0.0   6112  2316 tty1     S+   20:33   0:00      \_ xinit /home/start9/kiosk.sh -- /etc/X11/xinit/xserverrc :0 vt1 -keeptty -auth /tmp/serverauth.kJu1Iq1fc5
start9      5585  2.9  0.2 851940 70360 tty1     Sl   20:33   0:00          \_ /usr/lib/xorg/Xorg -nolisten tcp :0 vt1 -keeptty -auth /tmp/serverauth.kJu1Iq1fc5
start9      5852  0.0  0.0   2480   516 tty1     S    20:33   0:00          \_ /bin/sh /home/start9/kiosk.sh
start9      5873  0.0  0.0   2480    92 tty1     S    20:33   0:00              \_ /bin/sh /home/start9/kiosk.sh
start9      5881  0.0  0.0   2392   568 tty1     S    20:33   0:00              |   \_ sleep 15
start9      5875  0.2  0.0  24440 10848 tty1     S    20:33   0:00              \_ matchbox-window-manager -use_titlebar no
start9      5876 48.3  0.9 3046080 320796 tty1   Sl   20:33   0:05              \_ firefox-esr http://localhost --profile /tmp/tmp.wvSF6bc8pJ
start9      6218  0.3  0.1 210780 34620 tty1     Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -parentBuildID 20230724114731 -prefsLen 23202 -prefMapSize 
start9      6320  4.0  0.3 2435808 99392 tty1    Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 1 -isForBrowser -prefsLen 24139 -prefMapSize 21645
start9      6343 19.2  0.4 15077888 140948 tty1  Sl   20:33   0:01                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 2 -isForBrowser -prefsLen 24544 -prefMapSize 21645
start9      6481  4.2  0.3 2429840 110592 tty1   Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 3 -isForBrowser -prefsLen 32549 -prefMapSize 21645
start9      6488 35.6  0.3 2445144 106740 tty1   Sl   20:33   0:02                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 4 -isForBrowser -prefsLen 32584 -prefMapSize 21645
start9      6513  1.0  0.2 2381468 67684 tty1    Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 5 -isForBrowser -prefsLen 32759 -prefMapSize 21645
start9      6581  1.3  0.2 2382012 66044 tty1    Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 6 -isForBrowser -prefsLen 32796 -prefMapSize 21645
start9      6584  1.3  0.2 2382012 66408 tty1    Sl   20:33   0:00                  \_ /usr/lib/firefox-esr/firefox-esr -contentproc -childID 7 -isForBrowser -prefsLen 32796 -prefMapSize 21645
```

**Comment by gStart9** [comment]
Well I've managed to test this -- it's successfully running as the kiosk user, but still making plenty of calls to the internet.

Will do some more research - `dom.push.enabled` and/or `dom.push.connection.enabled` may need to be set to false.

If that's not fruitful I'll try librewolf and see if that would be an acceptable solution.  They've had similar debates about their defaults:
https://codeberg.org/librewolf/issues/issues/1558

**Comment by gStart9** [comment]
This PR relates to issues #2409 and #2069

**Comment by gStart9** [comment]
I tried these but it just killed functionality and didn't stop the mozilla requests:
https://github.com/pyllyukko/user.js

So I just cherry-picked from there to supplement Aiden's list.

Apparently there's no way to stop firefox, firefox-esr or librewolf from calling home to a ton of mozilla sites:
```
# tcpdump -i any -n 'port 53'
00:23:14.920822 wlp1s0 Out IP 192.168.0.19.43260 > 192.168.0.1.53: 41727+ A? firefox.settings.services.mozilla.com. (55)
00:23:14.920864 wlp1s0 Out IP 192.168.0.19.36316 > 192.168.0.1.53: 40619+ AAAA? firefox.settings.services.mozilla.com. (55)
00:23:14.920891 lo    In  IP 127.0.0.1.47826 > 127.0.0.1.53: 11098+ A? firefox.settings.services.mozilla.com. (55)
00:23:14.920919 lo    In  IP 127.0.0.1.41522 > 127.0.0.1.53: 58215+ AAAA? firefox.settings.services.mozilla.com. (55)
00:23:14.921006 lo    In  IP 127.0.0.1.53 > 127.0.0.1.41522: 58215 NXDomain- 0/0/0 (55)
00:23:14.921017 lo    In  IP 127.0.0.1.53 > 127.0.0.1.47826: 11098 NXDomain- 0/0/0 (55)
00:23:14.924795 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.43260: 41727 2/0/0 CNAME prod.remote-settings.prod.webservices.mozgcp.net., A 34.149.100.209 (133)
00:23:14.926159 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.36316: 40619 1/0/0 CNAME prod.remote-settings.prod.webservices.mozgcp.net. (117)
00:23:14.926392 wlp1s0 Out IP 192.168.0.19.50486 > 192.168.0.1.53: 18756+ AAAA? prod.remote-settings.prod.webservices.mozgcp.net. (66)
00:23:14.926433 lo    In  IP 127.0.0.1.38432 > 127.0.0.1.53: 20416+ AAAA? prod.remote-settings.prod.webservices.mozgcp.net. (66)
00:23:14.926470 lo    In  IP 127.0.0.1.57485 > 127.0.0.1.53: 27144+ A? prod.remote-settings.prod.webservices.mozgcp.net. (66)
00:23:14.926532 lo    In  IP 127.0.0.1.53 > 127.0.0.1.57485: 27144 NXDomain- 0/0/0 (66)
00:23:14.926544 lo    In  IP 127.0.0.1.53 > 127.0.0.1.38432: 20416 NXDomain- 0/0/0 (66)
00:23:14.938587 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.50486: 18756 0/1/0 (162)
00:23:15.004183 wlp1s0 Out IP 192.168.0.19.41318 > 192.168.0.1.53: 20876+ A? r3.o.lencr.org. (32)
00:23:15.004223 wlp1s0 Out IP 192.168.0.19.39333 > 192.168.0.1.53: 4079+ AAAA? r3.o.lencr.org. (32)
00:23:15.004254 lo    In  IP 127.0.0.1.34128 > 127.0.0.1.53: 62584+ AAAA? r3.o.lencr.org. (32)
00:23:15.004280 lo    In  IP 127.0.0.1.34865 > 127.0.0.1.53: 34658+ A? r3.o.lencr.org. (32)
00:23:15.004352 lo    In  IP 127.0.0.1.53 > 127.0.0.1.34865: 34658 NXDomain- 0/0/0 (32)
00:23:15.004363 lo    In  IP 127.0.0.1.53 > 127.0.0.1.34128: 62584 NXDomain- 0/0/0 (32)
00:23:15.013534 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.39333: 4079 4/0/0 CNAME o.lencr.edgesuite.net., CNAME a1887.dscq.akamai.net., AAAA 2600:1405:7400:d::17d9:9b0, AAAA 2600:1405:7400:d::17d9:99b (158)
00:23:15.013534 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.41318: 20876 4/0/0 CNAME o.lencr.edgesuite.net., CNAME a1887.dscq.akamai.net., A 23.38.100.180, A 23.38.100.195 (134)
00:23:15.081602 wlp1s0 Out IP 192.168.0.19.33636 > 192.168.0.1.53: 36521+ AAAA? shavar.services.mozilla.com. (45)
00:23:15.081662 wlp1s0 Out IP 192.168.0.19.37325 > 192.168.0.1.53: 60487+ A? shavar.services.mozilla.com. (45)
00:23:15.081691 lo    In  IP 127.0.0.1.43217 > 127.0.0.1.53: 22273+ AAAA? shavar.services.mozilla.com. (45)
00:23:15.081719 lo    In  IP 127.0.0.1.45812 > 127.0.0.1.53: 50988+ A? shavar.services.mozilla.com. (45)
00:23:15.081782 lo    In  IP 127.0.0.1.53 > 127.0.0.1.45812: 50988 NXDomain- 0/0/0 (45)
00:23:15.081797 lo    In  IP 127.0.0.1.53 > 127.0.0.1.43217: 22273 NXDomain- 0/0/0 (45)
00:23:15.087131 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.33636: 36521 1/0/0 CNAME shavar.prod.mozaws.net. (81)
00:23:15.090228 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.37325: 60487 4/0/0 CNAME shavar.prod.mozaws.net., A 34.214.148.106, A 54.185.54.63, A 44.240.83.93 (129)
00:23:15.090551 wlp1s0 Out IP 192.168.0.19.35329 > 192.168.0.1.53: 28227+ AAAA? shavar.prod.mozaws.net. (40)
00:23:15.090608 lo    In  IP 127.0.0.1.50170 > 127.0.0.1.53: 37288+ AAAA? shavar.prod.mozaws.net. (40)
00:23:15.090651 lo    In  IP 127.0.0.1.39823 > 127.0.0.1.53: 64963+ A? shavar.prod.mozaws.net. (40)
00:23:15.090717 lo    In  IP 127.0.0.1.53 > 127.0.0.1.39823: 64963 NXDomain- 0/0/0 (40)
00:23:15.090724 lo    In  IP 127.0.0.1.53 > 127.0.0.1.50170: 37288 NXDomain- 0/0/0 (40)
00:23:15.098019 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.35329: 28227 0/1/0 (125)
00:23:15.137481 wlp1s0 Out IP 192.168.0.19.48527 > 192.168.0.1.53: 36461+ A? push.services.mozilla.com. (43)
00:23:15.137522 wlp1s0 Out IP 192.168.0.19.42984 > 192.168.0.1.53: 63523+ AAAA? push.services.mozilla.com. (43)
00:23:15.137550 lo    In  IP 127.0.0.1.58414 > 127.0.0.1.53: 33049+ AAAA? push.services.mozilla.com. (43)
00:23:15.137576 lo    In  IP 127.0.0.1.34226 > 127.0.0.1.53: 19421+ A? push.services.mozilla.com. (43)
00:23:15.139593 lo    In  IP 127.0.0.1.53 > 127.0.0.1.34226: 19421 NXDomain- 0/0/0 (43)
00:23:15.139604 lo    In  IP 127.0.0.1.53 > 127.0.0.1.58414: 33049 NXDomain- 0/0/0 (43)
00:23:15.145677 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.42984: 63523 1/0/0 CNAME autopush.prod.mozaws.net. (81)
00:23:15.145677 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.48527: 36461 2/0/0 CNAME autopush.prod.mozaws.net., A 34.117.65.55 (97)
00:23:15.145908 wlp1s0 Out IP 192.168.0.19.47265 > 192.168.0.1.53: 989+ AAAA? autopush.prod.mozaws.net. (42)
00:23:15.145946 lo    In  IP 127.0.0.1.42391 > 127.0.0.1.53: 51902+ AAAA? autopush.prod.mozaws.net. (42)
00:23:15.145973 lo    In  IP 127.0.0.1.33968 > 127.0.0.1.53: 35767+ A? autopush.prod.mozaws.net. (42)
00:23:15.146051 lo    In  IP 127.0.0.1.53 > 127.0.0.1.33968: 35767 NXDomain- 0/0/0 (42)
00:23:15.146082 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42391: 51902 NXDomain- 0/0/0 (42)
00:23:15.157530 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.47265: 989 0/1/0 (127)
00:23:15.171841 wlp1s0 Out IP 192.168.0.19.59468 > 192.168.0.1.53: 8449+ A? ocsp.digicert.com. (35)
00:23:15.171879 wlp1s0 Out IP 192.168.0.19.39326 > 192.168.0.1.53: 53377+ AAAA? ocsp.digicert.com. (35)
00:23:15.171905 lo    In  IP 127.0.0.1.42167 > 127.0.0.1.53: 53552+ A? ocsp.digicert.com. (35)
00:23:15.171933 lo    In  IP 127.0.0.1.57284 > 127.0.0.1.53: 43998+ AAAA? ocsp.digicert.com. (35)
00:23:15.171995 lo    In  IP 127.0.0.1.53 > 127.0.0.1.57284: 43998 NXDomain- 0/0/0 (35)
00:23:15.172006 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42167: 53552 NXDomain- 0/0/0 (35)
00:23:15.172089 lo    In  IP 127.0.0.1.41129 > 127.0.0.1.53: 5323+ AAAA? push.services.mozilla.com. (43)
00:23:15.172113 lo    In  IP 127.0.0.1.57566 > 127.0.0.1.53: 7929+ A? push.services.mozilla.com. (43)
00:23:15.172129 lo    In  IP 127.0.0.1.53 > 127.0.0.1.41129: 5323 NXDomain- 0/0/0 (43)
00:23:15.172156 lo    In  IP 127.0.0.1.53 > 127.0.0.1.57566: 7929 NXDomain- 0/0/0 (43)
00:23:15.172207 lo    In  IP 127.0.0.1.49940 > 127.0.0.1.53: 52684+ AAAA? autopush.prod.mozaws.net. (42)
00:23:15.172230 lo    In  IP 127.0.0.1.57251 > 127.0.0.1.53: 13954+ A? autopush.prod.mozaws.net. (42)
00:23:15.172239 lo    In  IP 127.0.0.1.53 > 127.0.0.1.49940: 52684 NXDomain- 0/0/0 (42)
00:23:15.172261 lo    In  IP 127.0.0.1.53 > 127.0.0.1.57251: 13954 NXDomain- 0/0/0 (42)
00:23:15.189403 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.59468: 8449 4/0/0 CNAME ocsp.edge.digicert.com., CNAME fp2e7a.wpc.2be4.phicdn.net., CNAME fp2e7a.wpc.phicdn.net., A 192.229.211.108 (162)
00:23:15.190056 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.39326: 53377 3/1/0 CNAME ocsp.edge.digicert.com., CNAME fp2e7a.wpc.2be4.phicdn.net., CNAME fp2e7a.wpc.phicdn.net. (212)
00:23:15.190308 lo    In  IP 127.0.0.1.44856 > 127.0.0.1.53: 17082+ A? fp2e7a.wpc.phicdn.net. (39)
00:23:15.190336 lo    In  IP 127.0.0.1.41724 > 127.0.0.1.53: 14351+ AAAA? fp2e7a.wpc.phicdn.net. (39)
00:23:15.190426 lo    In  IP 127.0.0.1.53 > 127.0.0.1.41724: 14351 NXDomain- 0/0/0 (39)
00:23:15.190454 lo    In  IP 127.0.0.1.53 > 127.0.0.1.44856: 17082 NXDomain- 0/0/0 (39)
00:23:15.296816 wlp1s0 Out IP 192.168.0.19.39706 > 192.168.0.1.53: 12435+ AAAA? tracking-protection.cdn.mozilla.net. (53)
00:23:15.296857 wlp1s0 Out IP 192.168.0.19.58295 > 192.168.0.1.53: 14989+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.296883 lo    In  IP 127.0.0.1.41711 > 127.0.0.1.53: 48193+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.296909 lo    In  IP 127.0.0.1.52407 > 127.0.0.1.53: 54653+ AAAA? tracking-protection.cdn.mozilla.net. (53)
00:23:15.296987 lo    In  IP 127.0.0.1.53 > 127.0.0.1.52407: 54653 NXDomain- 0/0/0 (53)
00:23:15.296997 lo    In  IP 127.0.0.1.53 > 127.0.0.1.41711: 48193 NXDomain- 0/0/0 (53)
00:23:15.304762 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.39706: 12435 1/1/0 CNAME tracking-protection.prod.mozaws.net. (187)
00:23:15.305198 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.58295: 14989 2/0/0 CNAME tracking-protection.prod.mozaws.net., A 34.120.158.37 (118)
00:23:15.305418 wlp1s0 Out IP 192.168.0.19.56488 > 192.168.0.1.53: 25675+ AAAA? tracking-protection.prod.mozaws.net. (53)
00:23:15.305461 lo    In  IP 127.0.0.1.51980 > 127.0.0.1.53: 52583+ A? tracking-protection.prod.mozaws.net. (53)
00:23:15.305487 lo    In  IP 127.0.0.1.41880 > 127.0.0.1.53: 1676+ AAAA? tracking-protection.prod.mozaws.net. (53)
00:23:15.305567 lo    In  IP 127.0.0.1.53 > 127.0.0.1.41880: 1676 NXDomain- 0/0/0 (53)
00:23:15.305579 lo    In  IP 127.0.0.1.53 > 127.0.0.1.51980: 52583 NXDomain- 0/0/0 (53)
00:23:15.312890 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.56488: 25675 0/1/0 (138)
00:23:15.333067 lo    In  IP 127.0.0.1.50972 > 127.0.0.1.53: 31163+ A? r3.o.lencr.org. (32)
00:23:15.333097 lo    In  IP 127.0.0.1.43528 > 127.0.0.1.53: 19186+ AAAA? r3.o.lencr.org. (32)
00:23:15.333184 lo    In  IP 127.0.0.1.53 > 127.0.0.1.43528: 19186 NXDomain- 0/0/0 (32)
00:23:15.333193 lo    In  IP 127.0.0.1.53 > 127.0.0.1.50972: 31163 NXDomain- 0/0/0 (32)
00:23:15.333205 lo    In  IP 127.0.0.1.49602 > 127.0.0.1.53: 21364+ AAAA? a1887.dscq.akamai.net. (39)
00:23:15.333228 lo    In  IP 127.0.0.1.37867 > 127.0.0.1.53: 688+ A? a1887.dscq.akamai.net. (39)
00:23:15.333246 lo    In  IP 127.0.0.1.53 > 127.0.0.1.49602: 21364 NXDomain- 0/0/0 (39)
00:23:15.333275 lo    In  IP 127.0.0.1.53 > 127.0.0.1.37867: 688 NXDomain- 0/0/0 (39)
00:23:15.353790 wlp1s0 Out IP 192.168.0.19.38572 > 192.168.0.1.53: 35642+ A? firefox-settings-attachments.cdn.mozilla.net. (62)
00:23:15.353845 wlp1s0 Out IP 192.168.0.19.59121 > 192.168.0.1.53: 16522+ AAAA? firefox-settings-attachments.cdn.mozilla.net. (62)
00:23:15.353888 lo    In  IP 127.0.0.1.60086 > 127.0.0.1.53: 44990+ A? firefox-settings-attachments.cdn.mozilla.net. (62)
00:23:15.353926 lo    In  IP 127.0.0.1.45820 > 127.0.0.1.53: 25495+ AAAA? firefox-settings-attachments.cdn.mozilla.net. (62)
00:23:15.353994 lo    In  IP 127.0.0.1.53 > 127.0.0.1.45820: 25495 NXDomain- 0/0/0 (62)
00:23:15.354007 lo    In  IP 127.0.0.1.53 > 127.0.0.1.60086: 44990 NXDomain- 0/0/0 (62)
00:23:15.359570 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.38572: 35642 2/0/0 CNAME attachments.prod.remote-settings.prod.webservices.mozgcp.net., A 34.117.121.53 (152)
00:23:15.359596 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.59121: 16522 1/0/0 CNAME attachments.prod.remote-settings.prod.webservices.mozgcp.net. (136)
00:23:15.359846 wlp1s0 Out IP 192.168.0.19.39833 > 192.168.0.1.53: 1495+ AAAA? attachments.prod.remote-settings.prod.webservices.mozgcp.net. (78)
00:23:15.359890 lo    In  IP 127.0.0.1.54932 > 127.0.0.1.53: 41668+ AAAA? attachments.prod.remote-settings.prod.webservices.mozgcp.net. (78)
00:23:15.359922 lo    In  IP 127.0.0.1.34025 > 127.0.0.1.53: 9014+ A? attachments.prod.remote-settings.prod.webservices.mozgcp.net. (78)
00:23:15.359996 lo    In  IP 127.0.0.1.53 > 127.0.0.1.34025: 9014 NXDomain- 0/0/0 (78)
00:23:15.360006 lo    In  IP 127.0.0.1.53 > 127.0.0.1.54932: 41668 NXDomain- 0/0/0 (78)
00:23:15.365367 lo    In  IP 127.0.0.1.33131 > 127.0.0.1.53: 25169+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.365447 lo    In  IP 127.0.0.1.53 > 127.0.0.1.33131: 25169 NXDomain- 0/0/0 (53)
00:23:15.368641 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.39833: 1495 0/1/0 (217)
00:23:15.444962 lo    In  IP 127.0.0.1.46717 > 127.0.0.1.53: 64166+ AAAA? r3.o.lencr.org. (32)
00:23:15.444998 lo    In  IP 127.0.0.1.35588 > 127.0.0.1.53: 39026+ A? r3.o.lencr.org. (32)
00:23:15.445077 lo    In  IP 127.0.0.1.53 > 127.0.0.1.35588: 39026 NXDomain- 0/0/0 (32)
00:23:15.445088 lo    In  IP 127.0.0.1.53 > 127.0.0.1.46717: 64166 NXDomain- 0/0/0 (32)
00:23:15.445148 lo    In  IP 127.0.0.1.57514 > 127.0.0.1.53: 30008+ AAAA? a1887.dscq.akamai.net. (39)
00:23:15.445178 lo    In  IP 127.0.0.1.42870 > 127.0.0.1.53: 33947+ A? a1887.dscq.akamai.net. (39)
00:23:15.445210 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42870: 33947 NXDomain- 0/0/0 (39)
00:23:15.445217 lo    In  IP 127.0.0.1.53 > 127.0.0.1.57514: 30008 NXDomain- 0/0/0 (39)
00:23:15.450941 lo    In  IP 127.0.0.1.42750 > 127.0.0.1.53: 37435+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.451050 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42750: 37435 NXDomain- 0/0/0 (53)
00:23:15.498409 lo    In  IP 127.0.0.1.33948 > 127.0.0.1.53: 38764+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.498494 lo    In  IP 127.0.0.1.53 > 127.0.0.1.33948: 38764 NXDomain- 0/0/0 (53)
00:23:15.557204 lo    In  IP 127.0.0.1.59744 > 127.0.0.1.53: 25554+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.557288 lo    In  IP 127.0.0.1.53 > 127.0.0.1.59744: 25554 NXDomain- 0/0/0 (53)
00:23:15.598415 lo    In  IP 127.0.0.1.42684 > 127.0.0.1.53: 53304+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.598499 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42684: 53304 NXDomain- 0/0/0 (53)
00:23:15.687434 lo    In  IP 127.0.0.1.39188 > 127.0.0.1.53: 40951+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.687631 lo    In  IP 127.0.0.1.53 > 127.0.0.1.39188: 40951 NXDomain- 0/0/0 (53)
00:23:15.876914 lo    In  IP 127.0.0.1.51504 > 127.0.0.1.53: 11681+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.877045 lo    In  IP 127.0.0.1.53 > 127.0.0.1.51504: 11681 NXDomain- 0/0/0 (53)
00:23:15.906423 lo    In  IP 127.0.0.1.35192 > 127.0.0.1.53: 59237+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.906523 lo    In  IP 127.0.0.1.53 > 127.0.0.1.35192: 59237 NXDomain- 0/0/0 (53)
00:23:15.941751 lo    In  IP 127.0.0.1.54293 > 127.0.0.1.53: 20377+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.941837 lo    In  IP 127.0.0.1.53 > 127.0.0.1.54293: 20377 NXDomain- 0/0/0 (53)
00:23:15.975702 lo    In  IP 127.0.0.1.52370 > 127.0.0.1.53: 56935+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:15.975780 lo    In  IP 127.0.0.1.53 > 127.0.0.1.52370: 56935 NXDomain- 0/0/0 (53)
00:23:16.005017 lo    In  IP 127.0.0.1.40488 > 127.0.0.1.53: 20818+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.005097 lo    In  IP 127.0.0.1.53 > 127.0.0.1.40488: 20818 NXDomain- 0/0/0 (53)
00:23:16.055326 lo    In  IP 127.0.0.1.48573 > 127.0.0.1.53: 61502+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.055417 lo    In  IP 127.0.0.1.53 > 127.0.0.1.48573: 61502 NXDomain- 0/0/0 (53)
00:23:16.083835 lo    In  IP 127.0.0.1.35706 > 127.0.0.1.53: 24205+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.083959 lo    In  IP 127.0.0.1.53 > 127.0.0.1.35706: 24205 NXDomain- 0/0/0 (53)
00:23:16.113887 lo    In  IP 127.0.0.1.56775 > 127.0.0.1.53: 52829+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.113993 lo    In  IP 127.0.0.1.53 > 127.0.0.1.56775: 52829 NXDomain- 0/0/0 (53)
00:23:16.143378 lo    In  IP 127.0.0.1.54526 > 127.0.0.1.53: 21764+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.143487 lo    In  IP 127.0.0.1.53 > 127.0.0.1.54526: 21764 NXDomain- 0/0/0 (53)
00:23:16.180133 lo    In  IP 127.0.0.1.51736 > 127.0.0.1.53: 62185+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.180249 lo    In  IP 127.0.0.1.53 > 127.0.0.1.51736: 62185 NXDomain- 0/0/0 (53)
00:23:16.229626 lo    In  IP 127.0.0.1.50189 > 127.0.0.1.53: 18844+ A? tracking-protection.cdn.mozilla.net. (53)
00:23:16.229841 lo    In  IP 127.0.0.1.53 > 127.0.0.1.50189: 18844 NXDomain- 0/0/0 (53)
00:23:41.802261 wlp1s0 Out IP 192.168.0.19.53794 > 192.168.0.1.53: 61105+ A? safebrowsing.googleapis.com. (45)
00:23:41.802378 wlp1s0 Out IP 192.168.0.19.60595 > 192.168.0.1.53: 47452+ AAAA? safebrowsing.googleapis.com. (45)
00:23:41.802467 lo    In  IP 127.0.0.1.56026 > 127.0.0.1.53: 52891+ AAAA? safebrowsing.googleapis.com. (45)
00:23:41.802548 lo    In  IP 127.0.0.1.43372 > 127.0.0.1.53: 46218+ A? safebrowsing.googleapis.com. (45)
00:23:41.802719 lo    In  IP 127.0.0.1.53 > 127.0.0.1.43372: 46218 NXDomain- 0/0/0 (45)
00:23:41.802806 lo    In  IP 127.0.0.1.53 > 127.0.0.1.56026: 52891 NXDomain- 0/0/0 (45)
00:23:41.814447 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.60595: 47452 1/0/0 AAAA 2607:f8b0:400f:802::200a (73)
00:23:41.814925 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.53794: 61105 1/0/0 A 142.250.69.234 (61)
00:23:41.848604 wlp1s0 Out IP 192.168.0.19.48895 > 192.168.0.1.53: 61855+ AAAA? ocsp.pki.goog. (31)
00:23:41.848645 wlp1s0 Out IP 192.168.0.19.44850 > 192.168.0.1.53: 34858+ A? ocsp.pki.goog. (31)
00:23:41.848674 lo    In  IP 127.0.0.1.42764 > 127.0.0.1.53: 21708+ AAAA? ocsp.pki.goog. (31)
00:23:41.848703 lo    In  IP 127.0.0.1.53341 > 127.0.0.1.53: 27940+ A? ocsp.pki.goog. (31)
00:23:41.848794 lo    In  IP 127.0.0.1.53 > 127.0.0.1.53341: 27940 NXDomain- 0/0/0 (31)
00:23:41.848829 lo    In  IP 127.0.0.1.53 > 127.0.0.1.42764: 21708 NXDomain- 0/0/0 (31)
00:23:41.858035 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.44850: 34858 2/0/0 CNAME pki-goog.l.google.com., A 142.250.72.67 (82)
00:23:41.858172 wlp1s0 In  IP 192.168.0.1.53 > 192.168.0.19.48895: 61855 2/0/0 CNAME pki-goog.l.google.com., AAAA 2607:f8b0:400f:807::2003 (94)
```
Although thankfully (at least now, after these about:config changes) it doesn't seem to be contacting advertisers.

https://en.wikipedia.org/wiki/GNU_IceCat may be worth looking into, but it has no debian package so it's something we'd have to build if we wanted it in StartOS.

**Comment by gStart9** [comment]
Question for @dr-bonez: will this still be idempotent since we switched users from `start9` to `kiosk`?  I'm not actually sure how this thing starts.

**Review by dr-bonez — APPROVED** [review]

**Comment by dr-bonez** [comment]
no visible regressions. merging

**Pull request merged**
