### PR TITLE
Feat/combine uis

### PR DESCRIPTION
**Pull request by MattDHill**

### CODE REVIEW

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]
Is there an easy way to do this thank you thanks

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]
Fast/Combine-UIS Next-Minor

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Comment by dr-bonez** [comment]
testing reveals this always redirects to login, no request is made to the backend to the `state` rpc

**Comment by MattDHill** [comment]
Please test now that the downstream branch has been merged

**Comment by dr-bonez** [comment]
got further, found some backend bugs, but there's still issues:
- should call `init.logs.follow` instead of `server.logs.follow`
- progress bar shows at 0% even when receiving something like `overall: { done: 34, total: 73 }`
- `db.subscribe` is never called

**Review by Blu-J — APPROVED** [review]

**Pull request merged**
